import type { BiologyTopicConfig, ReviewMap, ReviewRating, ReviewRecord } from "@/types/questions";

export type TopicProgress = { bookmarks: Set<string>; needs: Set<string>; completed: Set<string>; reviews: ReviewMap };
const array = (key: string) => { try { const value=JSON.parse(localStorage.getItem(key) ?? "[]"); return new Set<string>(Array.isArray(value) ? value.filter((x): x is string => typeof x === "string") : []); } catch { return new Set<string>(); } };
const reviews = (key: string): ReviewMap => { try { const value=JSON.parse(localStorage.getItem(key) ?? "{}"); const result: ReviewMap={}; const entries=Array.isArray(value) ? value.map(x=>[x?.id ?? x?.questionId,x]) : Object.entries(value); for (const [id,raw] of entries) { if (!id || !raw) continue; if (typeof raw === "string") { const now=new Date().toISOString(); result[id]={rating:raw as ReviewRating,reviewedAt:now,dueAt:now,intervalDays:0,repetitions:0}; } else if (["again","hard","good","easy"].includes(raw.rating)) result[id]=raw as ReviewRecord; } return result; } catch { return {}; } };
export function readProgress(topic: BiologyTopicConfig): TopicProgress { const n=topic.storageNamespace; return {bookmarks:array(`${n}_bookmarks`),needs:array(`${n}_needspractice`),completed:array(`${n}_completed`),reviews:reviews(`${n}_reviews`)}; }
export function schedule(previous: ReviewRecord|undefined,rating: ReviewRating): ReviewRecord { const now=new Date(); let days=0; if(rating==="hard") days=Math.max(1,Math.round((previous?.intervalDays??1)*1.2)); if(rating==="good") days=Math.max(3,Math.round((previous?.intervalDays??1)*2)); if(rating==="easy") days=Math.max(7,Math.round((previous?.intervalDays??1)*3)); const delay=rating==="again"?10*60*1000:days*86400000; return {rating,reviewedAt:now.toISOString(),dueAt:new Date(now.getTime()+delay).toISOString(),intervalDays:days,repetitions:rating==="again"?0:(previous?.repetitions??0)+1}; }
export function saveRating(topic: BiologyTopicConfig,id:string,rating:ReviewRating){ const p=readProgress(topic); p.completed.add(id); if(rating==="again"||rating==="hard")p.needs.add(id); else p.needs.delete(id); p.reviews[id]=schedule(p.reviews[id],rating); const n=topic.storageNamespace; localStorage.setItem(`${n}_completed`,JSON.stringify([...p.completed])); localStorage.setItem(`${n}_needspractice`,JSON.stringify([...p.needs])); localStorage.setItem(`${n}_reviews`,JSON.stringify(Object.entries(p.reviews).map(([qid,r])=>({id:qid,...r})))); }
export function toggleBookmark(topic: BiologyTopicConfig,id:string){const p=readProgress(topic); if(p.bookmarks.has(id)){p.bookmarks.delete(id);}else{p.bookmarks.add(id);} localStorage.setItem(`${topic.storageNamespace}_bookmarks`,JSON.stringify([...p.bookmarks])); return p.bookmarks.has(id);}
