"use client";
/* Client-only localStorage hydration is intentionally performed after mount. */
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/purity, react-hooks/exhaustive-deps */
import { useEffect,useMemo,useState } from "react";
import Link from "next/link";
import { topicRegistry,questionKey } from "@/data/topics/registry";
import { readProgress,saveRating,toggleBookmark } from "@/lib/progress";
import type { MasteryQuestion,ReviewRating } from "@/types/questions";

type Mode="mixed"|"flashcards"|"bookmarks"|"due";
type Item={key:string;topic:(typeof topicRegistry)[number];question:MasteryQuestion;priority:number};
const labels={mixed:"Mixed Practice",flashcards:"Flashcards",bookmarks:"Bookmarked Review",due:"Due for Review"};
export default function RevisionCenter({initialMode="mixed",initialSubject,initialTopic}:{initialMode?:Mode;initialSubject?:string;initialTopic?:string}){
 const [mode,setMode]=useState<Mode>(initialMode),[subjects,setSubjects]=useState<string[]>(initialSubject?[initialSubject]:["biology","chemistry","physics"]),[topicIds,setTopicIds]=useState<string[]>(initialSubject&&initialTopic?[`${initialSubject}:${initialTopic}`]:[]),[ao,setAo]=useState("all"),[tier,setTier]=useState("all"),[practical,setPractical]=useState(false),[count,setCount]=useState(10),[order,setOrder]=useState("random"),[session,setSession]=useState<Item[]>([]),[index,setIndex]=useState(0),[flipped,setFlipped]=useState(false),[version,setVersion]=useState(0),[ready,setReady]=useState(false);
 useEffect(()=>setReady(true),[]);
 const all=useMemo(()=>{if(!ready)return[]; const now=Date.now(); return topicRegistry.flatMap(topic=>{const p=readProgress(topic); return topic.questions.map(question=>{const review=p.reviews[question.id]; return {key:questionKey(topic.subject??"biology",topic.id,question.id),topic,question,priority:(p.needs.has(question.id)?3:0)+(review?.rating==="again"?3:review?.rating==="hard"?2:0),bookmarked:p.bookmarks.has(question.id),due:!!review&&new Date(review.dueAt).getTime()<=now};});});},[ready,version]);
 const candidates=useMemo(()=>all.filter(item=>subjects.includes(item.topic.subject??"biology")&&(!topicIds.length||topicIds.includes(`${item.topic.subject}:${item.topic.id}`))&&(ao==="all"||item.question.assessmentObjective.includes(ao))&&(tier==="all"||(item.question.tier??item.question.difficulty)==tier)&&( !practical||/required practical|practical/i.test(`${item.question.question} ${item.question.subtopic} ${item.question.questionFamily??""}`))&&(mode!=="bookmarks"||item.bookmarked)&&(mode!=="due"||item.due)),[all,subjects,topicIds,ao,tier,practical,mode]);
 const start=()=>{let next=[...candidates]; next=order==="weakest"?next.sort((a,b)=>b.priority-a.priority):next.sort(()=>Math.random()-.5); setSession(next.slice(0,count));setIndex(0);setFlipped(false);};
 const rate=(rating:ReviewRating)=>{const item=session[index];if(!item)return;saveRating(item.topic,item.question.id,rating);setVersion(v=>v+1);setFlipped(false);setIndex(i=>Math.min(i+1,session.length));};
 useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(!session[index])return;if(e.code==="Space"){e.preventDefault();setFlipped(x=>!x);} if(flipped&&["1","2","3","4"].includes(e.key))rate((["again","hard","good","easy"] as ReviewRating[])[Number(e.key)-1]);};window.addEventListener("keydown",handler);return()=>window.removeEventListener("keydown",handler);});
 const current=session[index];
 return <main className="min-h-screen bg-[#f7f9fb] text-[#0f1f3d]"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-5"><Link href="/" className="font-black">Sci<span className="text-[#00a551]">Mastery</span></Link><Link href="/dashboard" className="font-bold text-[#00a551]">My Learning</Link></div></header><div className="mx-auto max-w-7xl px-4 py-10">
 <p className="text-sm font-bold uppercase tracking-widest text-[#00a551]">Revision centre</p><h1 className="mt-2 text-4xl font-black">{labels[mode]}</h1>
 <div className="mt-6 flex flex-wrap gap-2">{(Object.keys(labels) as Mode[]).map(m=><button key={m} onClick={()=>{setMode(m);setSession([])}} className={`rounded-xl px-4 py-2 font-bold ${mode===m?"bg-[#0f1f3d] text-white":"bg-white"}`}>{labels[m]}</button>)}</div>
 {!session.length&&<section className="mt-8 rounded-3xl border bg-white p-6 shadow-sm"><div className="grid gap-6 lg:grid-cols-2"><fieldset><legend className="font-extrabold">Subjects</legend><div className="mt-3 flex gap-4">{["biology","chemistry","physics"].map(s=><label key={s} className="capitalize"><input type="checkbox" checked={subjects.includes(s)} onChange={()=>setSubjects(x=>x.includes(s)?x.filter(y=>y!==s):[...x,s])}/> {s}</label>)}</div></fieldset><label className="font-extrabold">Topics<select multiple value={topicIds} onChange={e=>setTopicIds([...e.currentTarget.selectedOptions].map(x=>x.value))} className="mt-2 h-28 w-full rounded-xl border p-2 font-normal">{topicRegistry.filter(t=>subjects.includes(t.subject??"biology")).map(t=><option key={`${t.subject}:${t.id}`} value={`${t.subject}:${t.id}`}>{t.title}</option>)}</select></label><label>Assessment objective<select value={ao} onChange={e=>setAo(e.target.value)} className="ml-2 rounded-lg border p-2"><option value="all">All</option><option>AO1</option><option>AO2</option><option>AO3</option></select></label><label>Tier<select value={tier} onChange={e=>setTier(e.target.value)} className="ml-2 rounded-lg border p-2"><option value="all">All</option><option>Foundation</option><option>Higher</option><option>Both</option></select></label><label><input type="checkbox" checked={practical} onChange={e=>setPractical(e.target.checked)}/> Required practicals only</label><label>Questions <input type="number" min="1" max="50" value={count} onChange={e=>setCount(Number(e.target.value))} className="ml-2 w-20 rounded-lg border p-2"/></label><label>Order<select value={order} onChange={e=>setOrder(e.target.value)} className="ml-2 rounded-lg border p-2"><option value="random">Random</option><option value="weakest">Weakest first</option></select></label></div><p className="mt-5 text-sm text-[#5a6b82]">{candidates.length} questions match. Hold Ctrl/Cmd to select several topics.</p><button onClick={start} disabled={!candidates.length} className="mt-4 rounded-xl bg-[#00a551] px-6 py-3 font-bold text-white disabled:opacity-40">Start session</button>{!candidates.length&&<p className="mt-4 font-semibold text-[#5a6b82]">No questions match this selection. Adjust the filters or add bookmarks/reviews first.</p>}</section>}
 {session.length>0&&!current&&<section className="mt-8 rounded-3xl border bg-white p-10 text-center"><h2 className="text-2xl font-black">Session complete</h2><button onClick={()=>setSession([])} className="mt-5 rounded-xl bg-[#00a551] px-6 py-3 font-bold text-white">Start another</button></section>}
 {current&&<section className="mt-8"><div className="mb-3 flex justify-between text-sm font-bold"><span>{current.topic.title} · {current.question.assessmentObjective}</span><span>{index+1} of {session.length}</span></div><article onClick={()=>setFlipped(x=>!x)} className="min-h-72 cursor-pointer rounded-3xl border bg-white p-8 shadow-sm" tabIndex={0}><p className="text-xs font-bold uppercase tracking-widest text-[#00a551]">{flipped?"Answer / marking points":"Question"}</p>{!flipped?<h2 className="mt-5 text-2xl font-black leading-9">{current.question.question}</h2>:<div className="mt-5 space-y-3 text-lg">{current.question.markingPoints.map((p,i)=><p key={i}>✓ {p}</p>)}{current.question.modelAnswer&&<p className="rounded-xl bg-[#f7f9fb] p-4">{current.question.modelAnswer}</p>}</div>}<p className="mt-8 text-sm text-[#5a6b82]">Click card or press Space to {flipped?"hide":"reveal"}</p></article><div className="mt-4 flex flex-wrap gap-3"><button onClick={()=>{toggleBookmark(current.topic,current.question.id);setVersion(v=>v+1)}} className="rounded-xl border bg-white px-4 py-3 font-bold">Bookmark</button>{flipped&&(["again","hard","good","easy"] as ReviewRating[]).map((r,i)=><button key={r} onClick={()=>rate(r)} className="rounded-xl bg-[#0f1f3d] px-5 py-3 font-bold capitalize text-white">{i+1}. {r}</button>)}</div></section>}
 </div></main>;
}
